// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

export const SUPABASE_URL = "https://gogxicjaqpqbhsfzutij.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvZ3hpY2phcXBxYmhzZnp1dGlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzE2OTksImV4cCI6MjA2ODk0NzY5OX0.2VcH8dJ3qHyuoVihv_484KJgPvnJD1aJvkCDLbK_gCY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// ⚠️ ATENÇÃO: Supabase Auth foi DESABILITADO
// Use authAPI de @/integrations/auth/api-client para autenticação

// Interceptar fetch para bloquear requisições Supabase Auth
const originalFetch = window.fetch;
window.fetch = function(...args: Parameters<typeof fetch>) {
  const url = typeof args[0] === 'string' ? args[0] : args[0].url;
  
  // Bloquear TODAS as requisições para Supabase Auth
  if (url && url.includes('supabase.co/auth/v1/token')) {
    console.warn('🚫 Requisição Supabase Auth bloqueada:', url);
    return Promise.reject(new Error('Supabase Auth foi desabilitado. Use authAPI.login()'));
  }
  
  return originalFetch.apply(this, args);
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: {
      getItem: () => null, // Sempre retorna null para evitar leitura de tokens
      setItem: () => {}, // Ignora tentativas de salvar tokens
      removeItem: () => {}, // Ignora tentativas de remover tokens
    },
    persistSession: false,
    autoRefreshToken: false,
    detectSessionInUrl: false,
    flowType: 'pkce',
  },
  global: {
    headers: {
      // Não enviar tokens de auth
    }
  }
});

// Cria um client com headers adicionais (ex.: para RLS pública por header)
export const createSupabaseClientWithHeaders = (headers: Record<string, string>) =>
  createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: { headers },
    auth: {
      autoRefreshToken: false,
      persistSession: false,
    },
  });