// This file is automatically generated. Do not edit it directly.
// ⚠️⚠️⚠️ SUPABASE AUTH COMPLETAMENTE DESABILITADO ⚠️⚠️⚠️
// Use authAPI de @/integrations/auth/api-client para autenticação

import type { Database } from './types';

export const SUPABASE_URL = "https://gogxicjaqpqbhsfzutij.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvZ3hpY2phcXBxYmhzZnp1dGlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzE2OTksImV4cCI6MjA2ODk0NzY5OX0.2VcH8dJ3qHyuoVihv_484KJgPvnJD1aJvkCDLbK_gCY";

// 🚫 BLOQUEAR createClient - não criar cliente Supabase
// Criar mock que não faz nada
const createMockClient = () => {
  const mockAuth = {
    signInWithPassword: () => Promise.reject(new Error('Supabase Auth desabilitado. Use authAPI.login()')),
    signUp: () => Promise.reject(new Error('Supabase Auth desabilitado. Use authAPI.signup()')),
    signOut: () => Promise.resolve({ error: null }),
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
    getSession: () => Promise.resolve({ data: { session: null }, error: null }),
    getUser: () => Promise.resolve({ data: { user: null }, error: null }),
  };

  return {
    auth: mockAuth,
    from: () => {
      console.warn('⚠️ Tentativa de usar Supabase.from() - Use from() de @/integrations/db/client');
      return {
        select: () => ({ execute: () => Promise.resolve({ data: [], error: null }) }),
        insert: () => Promise.resolve({ data: null, error: new Error('Use PostgreSQL API') }),
        update: () => Promise.resolve({ data: null, error: new Error('Use PostgreSQL API') }),
        delete: () => Promise.resolve({ data: null, error: new Error('Use PostgreSQL API') }),
      };
    },
    channel: () => ({
      on: () => ({ subscribe: () => ({}) }),
      subscribe: () => ({}),
    }),
  } as any;
};

// Não importar createClient - usar mock
export const supabase = createMockClient() as any;

// Cria um client com headers adicionais (ex.: para RLS pública por header)
export const createSupabaseClientWithHeaders = (headers: Record<string, string>) =>
  createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: { headers },
    auth: {
      autoRefreshToken: false,
      persistSession: false,
    },
  });